blank_issues_enabled: false
contact_links:
  - name: "Zgłoszenie bez rejestracji w serwisie GitHub"
    url: "https://github.com/polskie-mapy/data/issues/427"
    about: Zgłoszenie problemów/propozycji bez rejestracji
